### ISSUE TITLE
Testing on Video

### ISSUE THREAD

**Issue by vinodbukya6** [ahsanalidev/flutter_nsfw#3]
Hi, Thank you so much for your work. I have tested flutter app on images it is working fine. When I run on Videos app is **crashing** can you help me on solving this and what is the video size or duration limit?

**Comment by ahsanalidev** [comment]
Thanks this is the way I have been using it and it works fine for me give it a try.
```dart
import 'dart:io' show Directory, Platform, File;
import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_nsfw/flutter_nsfw.dart';
import 'package:path_provider/path_provider.dart';

class NSFWDetector {
  NSFWDetector(this.modelPath, this.enableLog, this.isOpenGPU, this.numThreads);

  final String modelPath;
  final bool enableLog;
  final bool isOpenGPU;
  final int numThreads;

  bool isInitialized = false;

  Future<dynamic> detectInPhoto(String photoPath) async {
    if (!isInitialized) {
      Directory appDocDir = await getApplicationDocumentsDirectory();
      String appDocPath = appDocDir.path;
      var file = File(appDocPath + "/nsfw.tflite");
      if (!file.existsSync()) {
        var data = await rootBundle.load("assets/model/nsfw.tflite");
        final buffer = data.buffer;
        await file.writeAsBytes(
            buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
      }
      await FlutterNsfw.initNsfw(
        file.path,
      );
      isInitialized = true;
    }

    return FlutterNsfw.getPhotoNSFWScore(photoPath);
  }

  Future<dynamic> detectVideo(
    String videoPath,
    double nsfwThreshold,
    int width,
    int height,
  ) async {
    if (!isInitialized) {
      Directory appDocDir = await getApplicationDocumentsDirectory();
      String appDocPath = appDocDir.path;
      var file = File(appDocPath + "/nsfw.tflite");
      if (!file.existsSync()) {
        var data = await rootBundle.load("assets/model/nsfw.tflite");
        final buffer = data.buffer;
        await file.writeAsBytes(
            buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
      }
      await FlutterNsfw.initNsfw(
        file.path,
      );
      isInitialized = true;
    }
    final result = await FlutterNsfw.detectNSFWVideo(
        videoPath: videoPath,
        nsfwThreshold: nsfwThreshold,
        frameWidth: width,
        frameHeight: height,
        durationPerFrame: 1000);
    if (result != null) {
      print('the result is true');
      return result as bool;
    } else {
      print('this result is false');
      return false;
    }
  }
}
```

Then after this you can 
```dart
  Future<dynamic> detectNSFWImage(String photo) async {
    final nsfwStatus = await _nsfwDetector.detectInPhoto(photo);
    if (nsfwStatus > 0.80) {
      return true;
    } else {
      return false;
    }
  }

  Future<dynamic> detectNSFWVideo(String video, int width, int height) async {
    final nsfwStatus =
        await _nsfwDetector.detectVideo(video, 0.70, width, height);
    return nsfwStatus ?? false;
  }
```

**Comment by vinodbukya6** [comment]
Thank you so much @ahsanalidev . Will try and let you know.

**Comment by ahsanalidev** [comment]
Thanks

**Comment by vinodbukya6** [comment]
Hi @ahsanalidev, I have tested the APK with changes you mentioned. The APK is running fine on images but failing on videos(app closing issue). Do you have any idea on possible issues?

I have 2 questions.
1. What is the maximum duration of video for testing?
2. On video testing are you processing the whole video? How are you running tflite model on video(frame by frame)?

Thank you for your time.

**Comment by ahsanalidev** [comment]
I am not doing a real time actually I am converting the video to frames then running the tflite model on those frames to get nsfw score. I don't think there is any constrain on length of the video. If you are running it on a Simulator then it might be having a GPU constraints. Did you tried running it on real device?

**Comment by vinodbukya6** [comment]
I am running on Mobile device.

**Comment by vinodbukya6** [comment]
My Dart files are:

**video_class.dart** 

import 'dart:io' show Directory, Platform, File;
import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_nsfw/flutter_nsfw.dart';
import 'package:path_provider/path_provider.dart';

class NSFWDetector {
  NSFWDetector(this.modelPath, this.enableLog, this.isOpenGPU, this.numThreads);

  final String modelPath;
  final bool enableLog;
  final bool isOpenGPU;
  final int numThreads;

  bool isInitialized = false;

  Future<dynamic> detectInPhoto(String photoPath) async {
    if (!isInitialized) {
      Directory appDocDir = await getApplicationDocumentsDirectory();
      String appDocPath = appDocDir.path;
      var file = File(appDocPath + "/nsfw.tflite");
      if (!file.existsSync()) {
        var data = await rootBundle.load("assets/nsfw.tflite");
        final buffer = data.buffer;
        await file.writeAsBytes(
            buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
      }
      await FlutterNsfw.initNsfw(
        file.path,
      );
      isInitialized = true;
    }

    return FlutterNsfw.getPhotoNSFWScore(photoPath);
  }

  Future<dynamic> detectVideo(
    String videoPath,
    double nsfwThreshold,
    int width,
    int height,
  ) async {
    if (!isInitialized) {
      Directory appDocDir = await getApplicationDocumentsDirectory();
      String appDocPath = appDocDir.path;
      var file = File(appDocPath + "/nsfw.tflite");
      if (!file.existsSync()) {
        var data = await rootBundle.load("assets/nsfw.tflite");
        final buffer = data.buffer;
        await file.writeAsBytes(
            buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
      }
      await FlutterNsfw.initNsfw(
        file.path,
      );
      isInitialized = true;
    }
    final result = await FlutterNsfw.detectNSFWVideo(
        videoPath: videoPath,
        nsfwThreshold: nsfwThreshold,
        frameWidth: width,
        frameHeight: height,
        durationPerFrame: 1000);
    if (result != null) {
      print('the result is true');
      return result as bool;
    } else {
      print('this result is false');
      return false;
    }
  }
}

**main.dart**
import 'dart:async';
import 'dart:convert';
import 'dart:ffi';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_nsfw/flutter_nsfw.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path_provider/path_provider.dart';
import 'video_class.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
  }

  String imgPath = "";
  String videoPath = "";

  double result = 0.0;
  bool _isNSFW = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('contentDetection-V1'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              if (videoPath.isNotEmpty)
                Center(
                    child: Image.file(
                  File(videoPath),
                  width: 300,
                  height: 300,
                  fit: BoxFit.cover,
                )),
	          Text('The video is $_isNSFW'),
              ElevatedButton(
                child: Text('Select Video'),
                onPressed: () async {
                  final ImagePicker _picker = ImagePicker();
                  final XFile? image =
                      await _picker.pickVideo(source: ImageSource.gallery);
                  if (image != null) {
                    // String videoPath = '';
                    setState(() {
                      videoPath = image.path;
                    });
	                NSFWDetector _nsfwDetector = NSFWDetector('assets/nsfw.tflite', true, true, 2);
		            final nsfwStatus = await _nsfwDetector.detectVideo(videoPath, 0.70, 200, 300);	
                    setState(() {
                      _isNSFW = nsfwStatus;
                    });
                  }
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}

**Comment by ahsanalidev** [comment]
Hi, can you try again I have updated the package. The app might be crashing maybe because in the example I didn't gave a second thought and added async to a button but since dart is a single threaded language it causes the main thread to crash.
I have updated the package, you can try again now. 
``` dart
import 'dart:async';
import 'package:flutter_nsfw/flutter_nsfw.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'dart:io' show Directory, File;
import 'package:path_provider/path_provider.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(MyApp());
}

class NSFWDetector {
  NSFWDetector(this.modelPath, this.enableLog, this.isOpenGPU, this.numThreads);

  final String modelPath;
  final bool enableLog;
  final bool isOpenGPU;
  final int numThreads;

  bool isInitialized = false;

  Future<dynamic> detectInPhoto(String photoPath) async {
    if (!isInitialized) {
      Directory appDocDir = await getApplicationDocumentsDirectory();
      String appDocPath = appDocDir.path;
      var file = File(appDocPath + "/nsfw.tflite");
      if (!file.existsSync()) {
        var data = await rootBundle.load("assets/nsfw.tflite");
        final buffer = data.buffer;
        await file.writeAsBytes(
            buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
      }
      await FlutterNsfw.initNsfw(
        file.path,
      );
      isInitialized = true;
    }

    return FlutterNsfw.getPhotoNSFWScore(photoPath);
  }

  Future<dynamic> detectVideo(
    String videoPath,
    double nsfwThreshold,
    int width,
    int height,
  ) async {
    if (!isInitialized) {
      Directory appDocDir = await getApplicationDocumentsDirectory();
      String appDocPath = appDocDir.path;
      var file = File(appDocPath + "/nsfw.tflite");
      if (!file.existsSync()) {
        var data = await rootBundle.load("assets/nsfw.tflite");
        final buffer = data.buffer;
        await file.writeAsBytes(
            buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
      }
      await FlutterNsfw.initNsfw(
        file.path,
      );
      isInitialized = true;
    }
    final result = await FlutterNsfw.detectNSFWVideo(
        videoPath: videoPath,
        nsfwThreshold: nsfwThreshold,
        frameWidth: width,
        frameHeight: height,
        durationPerFrame: 1000);
    if (result != null) {
      print('the result is true');
      return result as bool;
    } else {
      print('this result is false');
      return false;
    }
  }
}

class MyApp extends StatefulWidget {
  const MyApp({
    Key? key,
  }) : super(key: key);
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  NSFWDetector _nsfwDetector =
      NSFWDetector('assets/model/nsfw.tflite', true, true, 2);
  Future<dynamic> detectNSFWImage(String photo) async {
    final nsfwStatus = await _nsfwDetector.detectInPhoto(photo);
    if (nsfwStatus > 0.80) {
      return true;
    } else {
      return false;
    }
  }

  Future<dynamic> detectNSFWVideo(String video, int width, int height) async {
    final nsfwStatus =
        await _nsfwDetector.detectVideo(video, 0.70, width, height);
    return nsfwStatus ?? false;
  }

  String imgPath = '';
  bool _isNSFW = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              if (imgPath.isNotEmpty)
                Center(
                    child: Image.file(
                  File(imgPath),
                  width: 300,
                  height: 300,
                  fit: BoxFit.cover,
                )),
              Text('The result is : $_isNSFW'),
              ElevatedButton(
                child: Text('Pick image'),
                onPressed: () async {
                  final ImagePicker _picker = ImagePicker();
                  final XFile? image =
                      await _picker.pickImage(source: ImageSource.gallery);
                  if (image != null) {
                    setState(() {
                      imgPath = image.path;
                    });
                    _isNSFW = await detectNSFWImage(imgPath);
                  }
                },
              ),
              Text('The video is $_isNSFW'),
              ElevatedButton(
                child: Text('Pick Video'),
                onPressed: () {
                  final ImagePicker _picker = ImagePicker();
                  _picker
                      .pickVideo(source: ImageSource.gallery)
                      .then((videoFile) {
                    if (videoFile != null) {
                      String videoPath = '';
                      setState(() {
                        videoPath = videoFile.path;
                      });
                      detectNSFWVideo(videoPath, 300, 200).then((isNSFW) {
                        setState(() {
                          _isNSFW = isNSFW;
                        });
                      });
                    }
                  });
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by vinodbukya6** [comment]
Thank you so much @ahsanalidev 

The **app-debug.apk (size: 170MB)** is working fine with images and videos but I don't know why **app-release.apk (size: 69MB)** is crashing the apk on videos. I will explore on the same. 

Is there any way to show the **confidence score** for video instead of true or false?
Can I show the **nsfw frame** from video ?

**Comment by ahsanalidev** [comment]
if your app  is crashing in release then In android/app/build.gradle, add the following setting in android block.

    aaptOptions {
        noCompress 'tflite'
        noCompress 'lite'
    }

and for the second part yeah we are actually getting confidence score I am converting it to bool you can directly return confidence score and For showing NSFW frame you have to pass path of the frame on the framework side of method channel and get it back in flutter side then you can get the frame too.

**Comment by vinodbukya6** [comment]
Thank you so much. 
For now working with Image functionality.

**Comment by vinodbukya6** [comment]
Hi @ahsanalidev,

Thank you so much for your work.
Finally I have solved Image and Video functionality issues. Now APK is working completely fine.

**Comment by ahsanalidev** [comment]
Thanks

**Comment by vinodbukya6** [comment]
Hi @ahsanalidev 
Currently busy in other projects, will create pull request next week.

Thank you.
